### ISSUE TITLE
Need "bcode" command to open VS Code directly, with "bcode <folder>" for immediate folder access.

### ISSUE THREAD

**Issue by rifatNR** [omranjamal/bookmark-cd#12]
We would like to introduce a command-line tool named bcode to streamline the process of opening Visual Studio Code directly from the terminal. This tool should support the following functionalities:

- Basic Command: Typing bcode should open Visual Studio Code without any additional arguments.

- Folder Argument: Typing bcode <folder> should directly open the specified folder in Visual Studio Code without requiring the user to select it manually.

**Comment by omranjamal** [comment]
This is probably outside the scope of this tool especially considering not everyone is using VSCode. A separate tool maybe?
